/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.dao.TelefonoDao;
import ec.edu.ups.dao.UsuarioDao;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
/**
 *
 * @author Anahi
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private UsuarioDao usuarioDao;
    private TelefonoDao telefonoDao;
    
    private ControladorUsuario controladorUsuario;

    private IniciarSesion ventanaIniciarSesion;
    private RegistrarUsuario ventanaRegistrarUsuario;
    private GestionTelefono ventanaGestionTelefono;
    private BuscarUsuario ventanaBuscar;
    private GestionUsuario ventanaGestionUsuario;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        gestionMenu.setVisible(false);
        cerrarSesionMenuItem.setVisible(false);

        telefonoDao = new TelefonoDao();
        usuarioDao = new UsuarioDao();
        controladorUsuario = new ControladorUsuario(usuarioDao, telefonoDao);

        ventanaIniciarSesion = new IniciarSesion(controladorUsuario, this);
        ventanaRegistrarUsuario = new RegistrarUsuario(controladorUsuario);
        ventanaGestionTelefono = new GestionTelefono(controladorUsuario);
        ventanaBuscar = new BuscarUsuario(controladorUsuario);
        ventanaGestionUsuario = new GestionUsuario(controladorUsuario);

        desktopPane.add(ventanaIniciarSesion);
        desktopPane.add(ventanaRegistrarUsuario);
        desktopPane.add(ventanaGestionTelefono);
        desktopPane.add(ventanaBuscar);
        desktopPane.add(ventanaGestionUsuario);
    }

    public JMenu getGestiónMenu() {
        return gestionMenu;
    }
    public JMenuItem getCerrarSesionMenuItem() {
        return cerrarSesionMenuItem;
    }
    public JMenuItem getIniciarSesionMenuItem() {
        return iniciarSesionMenuItem;
    }

    public JMenuItem getRegistrarUsuarioMenuItem() {
        return registroMenuItem;
    }
    
    //Método para cerrar las ventanas adicionales
    public void cerrarVentanas() {
        ventanaGestionTelefono.setVisible(false);
        ventanaIniciarSesion.setVisible(false);
        ventanaBuscar.setVisible(false);
        ventanaRegistrarUsuario.setVisible(false);
        ventanaGestionUsuario.setVisible(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        iniciarSesionMenuItem = new javax.swing.JMenuItem();
        cerrarSesionMenuItem = new javax.swing.JMenuItem();
        registroMenuItem = new javax.swing.JMenuItem();
        buscarMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        gestionMenu = new javax.swing.JMenu();
        gestionTelefonoMenu = new javax.swing.JMenuItem();
        gestionUsuarioMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setMnemonic('f');
        menu.setText("Menu");

        iniciarSesionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        iniciarSesionMenuItem.setMnemonic('o');
        iniciarSesionMenuItem.setText("Iniciar Sesión");
        iniciarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionMenuItemActionPerformed(evt);
            }
        });
        menu.add(iniciarSesionMenuItem);

        cerrarSesionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        cerrarSesionMenuItem.setText("Cerrar Sesión");
        cerrarSesionMenuItem.setToolTipText("");
        cerrarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionMenuItemActionPerformed(evt);
            }
        });
        menu.add(cerrarSesionMenuItem);

        registroMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        registroMenuItem.setMnemonic('s');
        registroMenuItem.setText("Registrar Usuario");
        registroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroMenuItemActionPerformed(evt);
            }
        });
        menu.add(registroMenuItem);

        buscarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        buscarMenuItem.setMnemonic('a');
        buscarMenuItem.setText("Buscar Usuario");
        buscarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMenuItemActionPerformed(evt);
            }
        });
        menu.add(buscarMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menu.add(exitMenuItem);

        menuBar.add(menu);

        gestionMenu.setMnemonic('f');
        gestionMenu.setText("Gestionar");

        gestionTelefonoMenu.setMnemonic('a');
        gestionTelefonoMenu.setText("Telefonos");
        gestionTelefonoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionTelefonoMenuActionPerformed(evt);
            }
        });
        gestionMenu.add(gestionTelefonoMenu);

        gestionUsuarioMenu.setMnemonic('o');
        gestionUsuarioMenu.setText("Usuarios");
        gestionUsuarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionUsuarioMenuActionPerformed(evt);
            }
        });
        gestionMenu.add(gestionUsuarioMenu);

        menuBar.add(gestionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void cerrarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Usted ha cerrado sesión");
        cerrarVentanas();

        gestionMenu.setVisible(false);
        cerrarSesionMenuItem.setVisible(false);

        registroMenuItem.setVisible(true);
        iniciarSesionMenuItem.setVisible(true);
    }//GEN-LAST:event_cerrarSesionMenuItemActionPerformed

    private void iniciarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionMenuItemActionPerformed
        cerrarVentanas();

        ventanaIniciarSesion.setVisible(true);
    }//GEN-LAST:event_iniciarSesionMenuItemActionPerformed

    private void registroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroMenuItemActionPerformed
        cerrarVentanas();
        ventanaRegistrarUsuario.setVisible(true);
    }//GEN-LAST:event_registroMenuItemActionPerformed

    private void buscarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMenuItemActionPerformed
        cerrarVentanas();
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_buscarMenuItemActionPerformed

    private void gestionTelefonoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionTelefonoMenuActionPerformed
        cerrarVentanas();
        ventanaGestionUsuario.setVisible(true);
    }//GEN-LAST:event_gestionTelefonoMenuActionPerformed

    private void gestionUsuarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuarioMenuActionPerformed
        cerrarVentanas();
        ventanaGestionTelefono.setVisible(true);

    }//GEN-LAST:event_gestionUsuarioMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarMenuItem;
    private javax.swing.JMenuItem cerrarSesionMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu gestionMenu;
    private javax.swing.JMenuItem gestionTelefonoMenu;
    private javax.swing.JMenuItem gestionUsuarioMenu;
    private javax.swing.JMenuItem iniciarSesionMenuItem;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem registroMenuItem;
    // End of variables declaration//GEN-END:variables

}
